version: '3'

services:
  mysql-db:
    container_name: "mysql-db"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
    depends_on:
      - mysql-db
  web:
    container_name: "web"
    build: .
    command: bash -c "pip install pymysql && python mysite/manage.py runserver 0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mysql-db
  node:
    container_name: "node"
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    # command: sh -c "cd argon-dashboard-react-master && npm start"
    command: sh -c "while :; do sleep 10; done"
    ports:
      - "3000:3000"